plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gelado.autoresposta'
    compileSdk 35

    defaultConfig {
        applicationId "com.gelado.autoresposta"
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName "2.1"
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
